### ISSUE TITLE
Rename .txt → .md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [OlexanderI/bhome#6]
There's nothing wrong with having your text files use the .txt extension, but if you change it to .md and use some Markdown like in `### НІКОЛИ НЕ РОЗМОВЛЯЙТЕ З НЕВІДОМИМИ` — then you'll have a nicely formatted preview and your files will still be considered text files.

**Comment by OlexanderI** [comment]
Good note, thank you @volodymyr-kushnir

**Comment by OlexanderI** [comment]
Done, updated by @KukuruzaAndrey
